;; Facet conformance test: gc-array/writev-nested-i8
;; Purpose: GC writev traverses a nested array in outer-index order.
;; Required profiles: core, memory32, gc-array, filesystem
;;
;; SPDX-License-Identifier: MIT

(module
  (type $bytes (array i8))
  (type $buffers (array (mut (ref null $bytes))))

  ;; Zero-length operations exercise the structural representation contract for
  ;; every logical byte-view width without introducing partial-I/O nondeterminism.
  (type $r8 (array (mut i8)))
  (type $r16 (array (mut i16)))
  (type $r32 (array (mut i32)))
  (type $r64 (array (mut i64)))
  (type $rv128 (array (mut v128)))
  (type $rr8 (array (mut (ref null $r8))))
  (type $rr16 (array (mut (ref null $r16))))
  (type $rr32 (array (mut (ref null $r32))))
  (type $rr64 (array (mut (ref null $r64))))
  (type $rrv128 (array (mut (ref null $rv128))))

  (type $w16 (array i16))
  (type $w32 (array i32))
  (type $w64 (array i64))
  (type $wv128 (array v128))
  (type $ww16 (array (mut (ref null $w16))))
  (type $ww32 (array (mut (ref null $w32))))
  (type $ww64 (array (mut (ref null $w64))))
  (type $wwv128 (array (mut (ref null $wv128))))

  (import "facet" "fs_preopen_get" (func $scratch (param i32) (result i32 i32)))
  (import "facet" "path_open_mem32_i8" (func $open (param i32 i32 i32 i32 i32 i32 i64) (result i32 i32)))

  (import "facet" "fd_read_array_i8" (func $read_i8 (param i32 (ref array) i64 i64) (result i64 i32)))
  (import "facet" "fd_read_array_i32" (func $read_i32 (param i32 (ref array) i64 i64) (result i64 i32)))
  (import "facet" "fd_read_array_i64" (func $read_i64 (param i32 (ref array) i64 i64) (result i64 i32)))

  (import "facet" "fd_pread_array_i8" (func $pread_i8 (param i32 i64 (ref array) i64 i64) (result i64 i32)))
  (import "facet" "fd_pread_array_i16" (func $pread_i16 (param i32 i64 (ref array) i64 i64) (result i64 i32)))
  (import "facet" "fd_pread_array_i32" (func $pread_i32 (param i32 i64 (ref array) i64 i64) (result i64 i32)))
  (import "facet" "fd_pread_array_i64" (func $pread_i64 (param i32 i64 (ref array) i64 i64) (result i64 i32)))
  (import "facet" "fd_pread_array_v128" (func $pread_v128 (param i32 i64 (ref array) i64 i64) (result i64 i32)))
  (import "facet" "fd_pwrite_array_i8" (func $pwrite_i8 (param i32 i64 (ref array) i64 i64) (result i64 i32)))
  (import "facet" "fd_pwrite_array_i16" (func $pwrite_i16 (param i32 i64 (ref array) i64 i64) (result i64 i32)))
  (import "facet" "fd_pwrite_array_i32" (func $pwrite_i32 (param i32 i64 (ref array) i64 i64) (result i64 i32)))
  (import "facet" "fd_pwrite_array_i64" (func $pwrite_i64 (param i32 i64 (ref array) i64 i64) (result i64 i32)))
  (import "facet" "fd_pwrite_array_v128" (func $pwrite_v128 (param i32 i64 (ref array) i64 i64) (result i64 i32)))

  (import "facet" "fd_writev_array_i8" (func $writev_i8 (param i32 (ref array) i32 i32) (result i64 i32)))
  (import "facet" "fd_writev_array_i16" (func $writev_i16 (param i32 (ref array) i32 i32) (result i64 i32)))
  (import "facet" "fd_writev_array_i32" (func $writev_i32 (param i32 (ref array) i32 i32) (result i64 i32)))
  (import "facet" "fd_writev_array_i64" (func $writev_i64 (param i32 (ref array) i32 i32) (result i64 i32)))
  (import "facet" "fd_writev_array_v128" (func $writev_v128 (param i32 (ref array) i32 i32) (result i64 i32)))
  (import "facet" "fd_readv_array_i8" (func $readv_i8 (param i32 (ref array) i32 i32) (result i64 i32)))
  (import "facet" "fd_readv_array_i16" (func $readv_i16 (param i32 (ref array) i32 i32) (result i64 i32)))
  (import "facet" "fd_readv_array_i32" (func $readv_i32 (param i32 (ref array) i32 i32) (result i64 i32)))
  (import "facet" "fd_readv_array_i64" (func $readv_i64 (param i32 (ref array) i32 i32) (result i64 i32)))
  (import "facet" "fd_readv_array_v128" (func $readv_v128 (param i32 (ref array) i32 i32) (result i64 i32)))
  (import "facet" "fd_read_mem32" (func $read (param i32 i32 i32 i32) (result i64 i32)))
  (import "facet" "fd_seek" (func $seek (param i32 i64 i32) (result i64 i32)))

  (memory 1)
  (data (i32.const 0) "nested.bin")

  (func $require-zero (param $n i64) (param $e i32)
    (if (i32.or (local.get $e) (i64.ne (local.get $n) (i64.const 0)))
      (then unreachable)))

  (func (export "run") (result i32)
    (local $x (ref $bytes)) (local $y (ref $bytes)) (local $b (ref $buffers))
    (local $r8 (ref $r8)) (local $r16 (ref $r16)) (local $r32 (ref $r32))
    (local $r64 (ref $r64)) (local $rv128 (ref $rv128))
    (local $rr8 (ref $rr8)) (local $rr16 (ref $rr16)) (local $rr32 (ref $rr32))
    (local $rr64 (ref $rr64)) (local $rrv128 (ref $rrv128))
    (local $ww16 (ref $ww16)) (local $ww32 (ref $ww32)) (local $ww64 (ref $ww64))
    (local $wwv128 (ref $wwv128))
    (local $dir i32) (local $fd i32) (local $e i32) (local $n i64) (local $off i64)

    ;; Preserve the original non-empty i8 writev ordering check.
    (local.set $x (array.new_fixed $bytes 3 (i32.const 65) (i32.const 66) (i32.const 67)))
    (local.set $y (array.new_fixed $bytes 3 (i32.const 68) (i32.const 69) (i32.const 70)))
    (local.set $b (array.new_default $buffers (i32.const 2)))
    (array.set $buffers (local.get $b) (i32.const 0) (local.get $x))
    (array.set $buffers (local.get $b) (i32.const 1) (local.get $y))
    (call $scratch (i32.const 0)) (local.set $e) (local.set $dir)
    (call $open (local.get $dir) (i32.const 0) (i32.const 0) (i32.const 10) (i32.const 0) (i32.const 5) (i64.const 63))
    (local.set $e) (local.set $fd)
    (call $writev_i8 (local.get $fd) (local.get $b) (i32.const 0) (i32.const 2))
    (local.set $e) (local.set $n)
    (if (i32.or (local.get $e) (i64.ne (local.get $n) (i64.const 6)))
      (then (return (i32.const 1))))
    (call $seek (local.get $fd) (i64.const 0) (i32.const 0)) (local.set $e) (local.set $off)
    (call $read (local.get $fd) (i32.const 0) (i32.const 64) (i32.const 6)) (local.set $e) (local.set $n)
    (if (i32.or (local.get $e)
          (i32.or (i32.ne (i32.load (i32.const 64)) (i32.const 1145258561))
                  (i32.ne (i32.load16_u (i32.const 68)) (i32.const 17989))))
      (then (return (i32.const 2))))

    ;; Allocate zero-length concrete GC arrays for every supported storage family.
    (local.set $r8 (array.new_default $r8 (i32.const 0)))
    (local.set $r16 (array.new_default $r16 (i32.const 0)))
    (local.set $r32 (array.new_default $r32 (i32.const 0)))
    (local.set $r64 (array.new_default $r64 (i32.const 0)))
    (local.set $rv128 (array.new_default $rv128 (i32.const 0)))

    ;; Sequential reads for the storage widths that previously had only import declarations.
    (call $read_i8 (local.get $fd) (local.get $r8) (i64.const 0) (i64.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $read_i32 (local.get $fd) (local.get $r32) (i64.const 0) (i64.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $read_i64 (local.get $fd) (local.get $r64) (i64.const 0) (i64.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))

    ;; Positional GC I/O exercises all five byte-view storage classes.
    (call $pread_i8 (local.get $fd) (i64.const 0) (local.get $r8) (i64.const 0) (i64.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $pread_i16 (local.get $fd) (i64.const 0) (local.get $r16) (i64.const 0) (i64.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $pread_i32 (local.get $fd) (i64.const 0) (local.get $r32) (i64.const 0) (i64.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $pread_i64 (local.get $fd) (i64.const 0) (local.get $r64) (i64.const 0) (i64.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $pread_v128 (local.get $fd) (i64.const 0) (local.get $rv128) (i64.const 0) (i64.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $pwrite_i8 (local.get $fd) (i64.const 0) (local.get $r8) (i64.const 0) (i64.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $pwrite_i16 (local.get $fd) (i64.const 0) (local.get $r16) (i64.const 0) (i64.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $pwrite_i32 (local.get $fd) (i64.const 0) (local.get $r32) (i64.const 0) (i64.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $pwrite_i64 (local.get $fd) (i64.const 0) (local.get $r64) (i64.const 0) (i64.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $pwrite_v128 (local.get $fd) (i64.const 0) (local.get $rv128) (i64.const 0) (i64.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))

    ;; Nested vectored GC I/O validates the outer array shape for each family.
    (local.set $rr8 (array.new_default $rr8 (i32.const 0)))
    (local.set $rr16 (array.new_default $rr16 (i32.const 0)))
    (local.set $rr32 (array.new_default $rr32 (i32.const 0)))
    (local.set $rr64 (array.new_default $rr64 (i32.const 0)))
    (local.set $rrv128 (array.new_default $rrv128 (i32.const 0)))
    (local.set $ww16 (array.new_default $ww16 (i32.const 0)))
    (local.set $ww32 (array.new_default $ww32 (i32.const 0)))
    (local.set $ww64 (array.new_default $ww64 (i32.const 0)))
    (local.set $wwv128 (array.new_default $wwv128 (i32.const 0)))

    (call $readv_i8 (local.get $fd) (local.get $rr8) (i32.const 0) (i32.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $readv_i16 (local.get $fd) (local.get $rr16) (i32.const 0) (i32.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $readv_i32 (local.get $fd) (local.get $rr32) (i32.const 0) (i32.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $readv_i64 (local.get $fd) (local.get $rr64) (i32.const 0) (i32.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $readv_v128 (local.get $fd) (local.get $rrv128) (i32.const 0) (i32.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $writev_i16 (local.get $fd) (local.get $ww16) (i32.const 0) (i32.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $writev_i32 (local.get $fd) (local.get $ww32) (i32.const 0) (i32.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $writev_i64 (local.get $fd) (local.get $ww64) (i32.const 0) (i32.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))
    (call $writev_v128 (local.get $fd) (local.get $wwv128) (i32.const 0) (i32.const 0))
    (local.set $e) (local.set $n) (call $require-zero (local.get $n) (local.get $e))

    (i32.const 0))
)
(assert_return (invoke "run") (i32.const 0))
