;; Facet conformance test: filesystem/dir-iterate-rewind
;; Purpose: Directory iteration uses the iterator as the stable name source and rewind resets pending state.
;; Required profiles: core, gc-array, filesystem, text
;;
;; SPDX-License-Identifier: MIT

(module
  (type $a8 (array (mut i8)))
  (type $a16 (array (mut i16)))
  (type $a32 (array (mut i32)))

  (import "facet" "fs_preopen_get" (func $get (param i32) (result i32 i32)))
  (import "facet" "dir_iter_open" (func $open (param i32) (result i32 i32)))
  (import "facet" "dir_iter_rewind" (func $rewind (param i32) (result i32)))
  (import "facet" "dir_iter_next_len_i8" (func $len8 (param i32 i32) (result i64 i32 i64 i32 i32)))
  (import "facet" "dir_iter_next_len_i16" (func $len16 (param i32 i32) (result i64 i32 i64 i32 i32)))
  (import "facet" "dir_iter_next_len_i32" (func $len32 (param i32 i32) (result i64 i32 i64 i32 i32)))
  (import "facet" "dir_iter_next_mem32_i8" (func $mem32_i8 (param i32 i32 i32 i32 i32) (result i64 i32 i64 i32 i32)))
  (import "facet" "dir_iter_next_mem32_i16" (func $mem32_i16 (param i32 i32 i32 i32 i32) (result i64 i32 i64 i32 i32)))
  (import "facet" "dir_iter_next_mem32_i32" (func $mem32_i32 (param i32 i32 i32 i32 i32) (result i64 i32 i64 i32 i32)))
  (import "facet" "dir_iter_next_mem64_i8" (func $mem64_i8 (param i32 i32 i32 i64 i64) (result i64 i32 i64 i32 i32)))
  (import "facet" "dir_iter_next_mem64_i16" (func $mem64_i16 (param i32 i32 i32 i64 i64) (result i64 i32 i64 i32 i32)))
  (import "facet" "dir_iter_next_mem64_i32" (func $mem64_i32 (param i32 i32 i32 i64 i64) (result i64 i32 i64 i32 i32)))
  (import "facet" "dir_iter_next_into_array_i8" (func $into_i8 (param i32 i32 (ref array) i32 i32) (result i64 i32 i64 i32 i32)))
  (import "facet" "dir_iter_next_into_array_i16" (func $into_i16 (param i32 i32 (ref array) i32 i32) (result i64 i32 i64 i32 i32)))
  (import "facet" "dir_iter_next_into_array_i32" (func $into_i32 (param i32 i32 (ref array) i32 i32) (result i64 i32 i64 i32 i32)))
  (import "facet" "dir_iter_next_array_i8" (func $array_i8 (param i32 i32) (result (ref null $a8) i32 i64 i32 i32)))
  (import "facet" "dir_iter_next_array_i16" (func $array_i16 (param i32 i32) (result (ref null $a16) i32 i64 i32 i32)))
  (import "facet" "dir_iter_next_array_i32" (func $array_i32 (param i32 i32) (result (ref null $a32) i32 i64 i32 i32)))

  (memory 1)
  (memory i64 1)

  (func $check-rewind (param $iter i32) (result i32)
    (call $rewind (local.get $iter)))

  (func (export "run") (result i32)
    (local $dir i32) (local $iter i32) (local $e i32)
    (local $name_len i64) (local $type i32) (local $inode i64) (local $done i32)
    (local $a8 (ref $a8)) (local $a16 (ref $a16)) (local $a32 (ref $a32))
    (local $name8 (ref null $a8)) (local $name16 (ref null $a16)) (local $name32 (ref null $a32))

    (call $get (i32.const 0)) (local.set $e) (local.set $dir)
    (if (local.get $e) (then (return (local.get $e))))
    (call $open (local.get $dir)) (local.set $e) (local.set $iter)
    (if (local.get $e) (then (return (local.get $e))))

    ;; Length-only iteration in every text width.
    (call $len8 (local.get $iter) (i32.const 0))
    (local.set $e) (local.set $done) (local.set $inode) (local.set $type) (local.set $name_len)
    (if (local.get $e) (then (return (local.get $e))))
    (if (call $check-rewind (local.get $iter)) (then (return (i32.const 101))))
    (call $len16 (local.get $iter) (i32.const 0))
    (local.set $e) (local.set $done) (local.set $inode) (local.set $type) (local.set $name_len)
    (if (local.get $e) (then (return (local.get $e))))
    (if (call $check-rewind (local.get $iter)) (then (return (i32.const 102))))
    (call $len32 (local.get $iter) (i32.const 0))
    (local.set $e) (local.set $done) (local.set $inode) (local.set $type) (local.set $name_len)
    (if (local.get $e) (then (return (local.get $e))))
    (if (call $check-rewind (local.get $iter)) (then (return (i32.const 103))))

    ;; Memory32 representations.
    (call $mem32_i8 (local.get $iter) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 256))
    (local.set $e) (local.set $done) (local.set $inode) (local.set $type) (local.set $name_len)
    (if (local.get $e) (then (return (local.get $e))))
    (if (call $check-rewind (local.get $iter)) (then (return (i32.const 104))))
    (call $mem32_i16 (local.get $iter) (i32.const 0) (i32.const 0) (i32.const 512) (i32.const 256))
    (local.set $e) (local.set $done) (local.set $inode) (local.set $type) (local.set $name_len)
    (if (local.get $e) (then (return (local.get $e))))
    (if (call $check-rewind (local.get $iter)) (then (return (i32.const 105))))
    (call $mem32_i32 (local.get $iter) (i32.const 0) (i32.const 0) (i32.const 1024) (i32.const 256))
    (local.set $e) (local.set $done) (local.set $inode) (local.set $type) (local.set $name_len)
    (if (local.get $e) (then (return (local.get $e))))
    (if (call $check-rewind (local.get $iter)) (then (return (i32.const 106))))

    ;; Memory64 representations.
    (call $mem64_i8 (local.get $iter) (i32.const 0) (i32.const 1) (i64.const 0) (i64.const 256))
    (local.set $e) (local.set $done) (local.set $inode) (local.set $type) (local.set $name_len)
    (if (local.get $e) (then (return (local.get $e))))
    (if (call $check-rewind (local.get $iter)) (then (return (i32.const 107))))
    (call $mem64_i16 (local.get $iter) (i32.const 0) (i32.const 1) (i64.const 512) (i64.const 256))
    (local.set $e) (local.set $done) (local.set $inode) (local.set $type) (local.set $name_len)
    (if (local.get $e) (then (return (local.get $e))))
    (if (call $check-rewind (local.get $iter)) (then (return (i32.const 108))))
    (call $mem64_i32 (local.get $iter) (i32.const 0) (i32.const 1) (i64.const 1024) (i64.const 256))
    (local.set $e) (local.set $done) (local.set $inode) (local.set $type) (local.set $name_len)
    (if (local.get $e) (then (return (local.get $e))))
    (if (call $check-rewind (local.get $iter)) (then (return (i32.const 109))))

    ;; Caller-owned GC arrays.
    (local.set $a8 (array.new_default $a8 (i32.const 256)))
    (local.set $a16 (array.new_default $a16 (i32.const 256)))
    (local.set $a32 (array.new_default $a32 (i32.const 256)))
    (call $into_i8 (local.get $iter) (i32.const 0) (local.get $a8) (i32.const 0) (i32.const 256))
    (local.set $e) (local.set $done) (local.set $inode) (local.set $type) (local.set $name_len)
    (if (local.get $e) (then (return (local.get $e))))
    (if (call $check-rewind (local.get $iter)) (then (return (i32.const 110))))
    (call $into_i16 (local.get $iter) (i32.const 0) (local.get $a16) (i32.const 0) (i32.const 256))
    (local.set $e) (local.set $done) (local.set $inode) (local.set $type) (local.set $name_len)
    (if (local.get $e) (then (return (local.get $e))))
    (if (call $check-rewind (local.get $iter)) (then (return (i32.const 111))))
    (call $into_i32 (local.get $iter) (i32.const 0) (local.get $a32) (i32.const 0) (i32.const 256))
    (local.set $e) (local.set $done) (local.set $inode) (local.set $type) (local.set $name_len)
    (if (local.get $e) (then (return (local.get $e))))
    (if (call $check-rewind (local.get $iter)) (then (return (i32.const 112))))

    ;; Host-allocated GC arrays.
    (call $array_i8 (local.get $iter) (i32.const 0))
    (local.set $e) (local.set $done) (local.set $inode) (local.set $type) (local.set $name8)
    (if (local.get $e) (then (return (local.get $e))))
    (if (call $check-rewind (local.get $iter)) (then (return (i32.const 113))))
    (call $array_i16 (local.get $iter) (i32.const 0))
    (local.set $e) (local.set $done) (local.set $inode) (local.set $type) (local.set $name16)
    (if (local.get $e) (then (return (local.get $e))))
    (if (call $check-rewind (local.get $iter)) (then (return (i32.const 114))))
    (call $array_i32 (local.get $iter) (i32.const 0))
    (local.set $e) (local.set $done) (local.set $inode) (local.set $type) (local.set $name32)
    (local.get $e))
)
(assert_return (invoke "run") (i32.const 0))
